### ISSUE TITLE
BUG: For you page empty when not logged in and click on musish logo

### ISSUE THREAD

**Issue by jamesjarvis** [Musish/Musish#312]
**Describe the bug**
When not logged in, you are still able to click on the musish logo which redirects you to an empty for you page.

**To Reproduce**
1. Be not logged in
2. Click on the musish logo
3. See 'For you' page as empty
4. Profit

**Expected behavior**
Should redirect to login page (maybe we should set this up as an actual page '/login' rather than just being accessible through state)

**Comment by SpartakusMd** [comment]
This bug was introduced by me as I didn't test the link while being logged out. I made a PR so you get to the page `Browse` if you are not logged in and to the page `For you` if you are logged in.

I don't see the reason to have a separate page for login as the login happens in the popup window and it will be somehow duplicate.
