### ISSUE TITLE
BUG: Keno Kirsch - artist is not correct shown

### ISSUE THREAD

**Issue by Kirschke007** [Musish/Musish#379]
**Describe the bug**
When I am searching for an Artist (Keno Kirsch), then is shown the wrong artist, but the songs from the official Keno Kirsch artist are there!!
Here I give you the official iTunes link to Keno Kirsch:
[https://itunes.apple.com/de/artist/keno-kirsch/1414480826](https://itunes.apple.com/de/artist/keno-kirsch/1414480826)

**To Reproduce**
1. Go to 'Search music'
2. Search for **Keno Kirsch**
3. Scroll down to Artist - Keno Kirsch
4. See error - There will be shown Kenneth Macmillan and NOT the artist who should be shown [**Keno Kirsch**](https://itunes.apple.com/de/artist/keno-kirsch/1414480826)!!!!!!!!

**Expected behavior**
It have to show the right artist on this place!
Here is the official iTunes link to the artist:
[https://itunes.apple.com/de/artist/keno-kirsch/1414480826](https://itunes.apple.com/de/artist/keno-kirsch/1414480826)

**Screenshots**
 - **THATS NOT CORRECT**
![musish bug](https://user-images.githubusercontent.com/47913790/57509840-97c7df80-7305-11e9-94a4-3ddb92b90823.png)

- **THIS IS CORRECT**
![iTunes Keno Kirsch](https://user-images.githubusercontent.com/47913790/57510036-04db7500-7306-11e9-9c0e-064d761ed36b.PNG) 

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 74.0.3729.131 (Officiall Build) (64-Bit)

**Additional context**
I am the artist Keno Kirsch, so i would be happy if you could fix it as fast as it is possible!! 
Thank you! Keno Kirsch
email: [kenokirsch@icloud.com](mailto:kenokirsch@icloud.com)

**Comment by jamesjarvis** [comment]
Hi Keno, unfortunately this is not our issue, as we do not actively store any artist information ourselves. We consume information from Genius.com. Since you are not a listed artist on there it just picks up the next most similar artist name, which is apparently Kenneth Macmillan. If you would like your information to be viewable on Musish, please make your page on genius! https://genius.com/Genius-how-genius-works-annotated
