### ISSUE TITLE
FEATURE: Audio Change & Others

### ISSUE THREAD

**Issue by zzzander** [Musish/Musish#388]
My volume control doesn't work for me. It could possibly be my browser (**Brave Browser**) but it doesn't work.
Features to possibly add: a 'Date Added' option under the "**Songs**" tab - I listen to my music in order from when I added it from that tab, might be cool to have.
Also, maybe a "Night Mode" visual enhancement? Love the app though, very helpful! iTunes is HORRIBLE!

**Comment by jamesjarvis** [comment]
Dark mode is a loooong requested feature! Covered by #206 and it under on/off active development. If you would like to make your own feel free to submit a PR! Any and all contributions are welcome, albeit we are rather slow to review.
Date added is something I don't believe we can retrieve at the moment, so may be a music kit limitation.
Volume is broken at the moment, again covered in #387 but will be hopefully be fixed with a future release of music kit.
We are glad you enjoy it! Please continue using and contributing :)

**Comment by BrychanOdlum** [comment]
Thanks for the feedback!

Closing this issue as the volume control issue has been resolved.
